### ISSUE TITLE
metawrap errors

### ISSUE THREAD

**Issue by shuchong200** [bxlab/metaWRAP#411]
Hello!

Has anyone else meet the error of OS errot during using metawrap, the error as below:
  onerror(os.remove, fullname, sys.exc_info())
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-RwWALq/.nfs000003000949c3c8000a13be'
    onerror(os.remove, fullname, sys.exc_info())
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-eVFinc/.nfs000003000949c4c1000a13c7'
    onerror(os.remove, fullname, sys.exc_info())
OSError: [Errno 16] Device or resource busy: 'binsAB.tmp/pymp-vtZKkO/.nfs0000030009457382000a13ce'
    onerror(os.remove, fullname, sys.exc_info())
OSError: [Errno 16] Device or resource busy: 'binsAB.tmp/pymp-zP5bA1/.nfs0000030009457469000a13d5'
    onerror(os.remove, fullname, sys.exc_info())
OSError: [Errno 16] Device or resource busy: 'binsABC.tmp/pymp-p34th4/.nfs00000300094576f1000a13dd'
    onerror(os.remove, fullname, sys.exc_info())
OSError: [Errno 16] Device or resource busy: 'binsABC.tmp/pymp-qTRoM3/.nfs00000300094581a8000a13e5'

How to fix them?

**Comment by B-1991-ing** [comment]
Dear [shuchong200](https://github.com/shuchong200),

Thank you very much for sharing your error message. Did you finally solve this problem? Or you just ignored it?

Below is my similar error message.

Traceback (most recent call last):
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsBC.tmp/pymp-6ygw0c/.nfs00000006e3d6e5e500003416'

But, I actually got " BIN_REFINEMENT PIPELINE FINISHED SUCCESSFULLY!" in my metawrap_bin_refinement.log.

Best,

Bing

**Comment by nashanghenzan** [comment]
> Hello!
> 
> Has anyone else meet the error of OS errot during using metawrap, the error as below: onerror(os.remove, fullname, sys.exc_info()) OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-RwWALq/.nfs000003000949c3c8000a13be' onerror(os.remove, fullname, sys.exc_info()) OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-eVFinc/.nfs000003000949c4c1000a13c7' onerror(os.remove, fullname, sys.exc_info()) OSError: [Errno 16] Device or resource busy: 'binsAB.tmp/pymp-vtZKkO/.nfs0000030009457382000a13ce' onerror(os.remove, fullname, sys.exc_info()) OSError: [Errno 16] Device or resource busy: 'binsAB.tmp/pymp-zP5bA1/.nfs0000030009457469000a13d5' onerror(os.remove, fullname, sys.exc_info()) OSError: [Errno 16] Device or resource busy: 'binsABC.tmp/pymp-p34th4/.nfs00000300094576f1000a13dd' onerror(os.remove, fullname, sys.exc_info()) OSError: [Errno 16] Device or resource busy: 'binsABC.tmp/pymp-qTRoM3/.nfs00000300094581a8000a13e5'
> 
> How to fix them?

the issue has been solved? I meet the same issue and don't solve the problem

**Comment by B-1991-ing** [comment]
I didn't solve this issue, but still used the bins. 

I reran 10 times on the exact same dataset with different running memory settings, all generated bins were exactly same, so the error message doesn't affect output bins at all. So, finally, I just used the bins from the first time running. 

Some experts said it is due to the memory problem, I set the mem=1500gb, same error. But bins were same.

**Comment by nashanghenzan** [comment]
> I didn't solve this issue, but still used the bins.
> 
> I reran 10 times on the exact same dataset with different running memory settings, all generated bins were exactly same, so the error message doesn't affect output bins at all. So, finally, I just used the bins from the first time running.
> 
> Some experts said it is due to the memory problem, I set the mem=1500gb, same error. But bins were same.

i have solved the issue, `vim bin_refinement.sh`, delete `--tmpdir ${bin_set}.tmp`(4 totally). i found that if you don't s3 the issue, the outcome from checkm is uncomplete
