### ISSUE TITLE
checkm error in bin_refinement

### ISSUE THREAD

**Issue by yunha** [bxlab/metaWRAP#48]
In the bin_refinement module log I am seeing this checkm error: 

[CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 47 bins with 16 threads:
    Finished processing 47 of 47 (100.00%) bins.
Traceback (most recent call last):
  File "/home/yunha/miniconda2/envs/metawrap-env/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/home/yunha/miniconda2/envs/metawrap-env/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/yunha/miniconda2/envs/metawrap-env/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/home/yunha/miniconda2/envs/metawrap-env/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-yl1pXc/.nfs00000000011a2d100000022f'
  Saving HMM info to file.

And as a result (I believe) I am getting very low completeness values for the bins and thus, "There are 0 'good' bins found in binsA! (>50% completion and <10% contamination)" log for all combinations of bin sets. 

Do you know what this error is?

**Comment by yunha** [comment]
I managed to fix the OSerror by putting the .tmp files in the /tmp directory but I still get very low completeness values or very high contamination for the bin stats and none of the bins are 'good' bins. Any idea what's going on? I've previously ran metabat2 on this data and got some decent bins before so this is baffling to me.

**Comment by ursky** [comment]
Strange... i have seen this error before but it never game me any issues. What do `metabat2.stats` look like compared to `metaWRAP.stats`? I am wondering if its the refinement bin that is failing of the initial bin predictions were bad to begin with.

**Comment by yunha** [comment]
I think you are right, the initial bin predictions were bad to begin with. Probably due to the bwa mem error that I posted earlier. I made bin_sets manually and ran bin_refinement and it looks reasonable now. Is there any way metaWRAP can support interleaved paired-end reads file as input instead of deinterleaved files?  I have already performed barcoding and quality trimming on the interleaved read file that I have used for assembly and since  splitting the file thereafter causes error when aligning the reads to the assembly, I will have to regenerate the reads files from scratch which will take bit of time for me..

**Comment by ursky** [comment]
In your initial binning run, did bwa produce `.sam` files? Do they look very small? If not a common explanation for shitty bins is that you accidentally provided the `Binning` module only one set of reads (the combined reads) instead of your replicates. Could that be the case here?

Unfortunately using de-interweaved reads would be tricky at this point. If you de-interweave them yourself, you can put them through the `Read_qc` module (you can skip the BMTAGGER step for speed), which makes sure all the reads are properly linked and accounted for.

**Comment by yunha** [comment]
It created no sam files. (Should it have?) Just a bam file actually and it is a pretty big file. I will try running the reads through reads_qc module and see if bwa mem works correctly!

**Comment by yunha** [comment]
That's weird because the only thing that I did differently to create bins manually was to input the bam file made using interleaved reads file. I didn't run the kraken module before but that could not have been the issue for shitty binning right?

**Comment by ursky** [comment]
Nothing to do with Kraken. Just to clarify - you did some binning by manually aligning the reads and running a binner by yourself (like metabat or maxbin), which produced good bins as determined with the Bin_refinement module? But then you tried using the Binning module, and got bad bins? If that is the case, can you show me the command you used to make the bam file that worked?

**Comment by yunha** [comment]
That is correct. 

bwa mem -t 200 contigs.fa paired_reads.fq  | samtools sort --threads 200 > reads.bam

I used this reads.bam file for metabat2, metabat1, and maxbin2 and they all generated decent bins. but, running the module using manually deinterleaved reads files generated bad bins.

**Comment by yunha** [comment]
So it turns out there was something wrong with the assembled contigs I was using for this module. My bad. Everything worked as expected once I fixed the contigs.

**Comment by ursky** [comment]
Excellent! Glad you figured it out.

**Comment by JinqunHuang** [comment]
@ursky dear Gherman,

I got similar errors by running "metawrap bin_refinement" with 1.18 version

I have tried to set a clear output folder, but the errors still exist.

metawrap bin_refinement -o 5.bining/AS101-BIN_REFINEMENT -t 8 -A 5.bining/AS101/INITIAL_BINNING/metabat2_bins/ -B 5.bining/AS101/INITIAL_BINNING/maxbin2_bins/ -C 5.bining/AS101/INITIAL_BINNING/concoct_bins/ -c 50 -x 10

 [CheckM - tree] Placing bins in reference genome tree.
...
Finished processing 75 of 75 (100.00%) bins.
Traceback (most recent call last):
  File "/hwfssz4/BC_COM_FP/BC_CCP/Micro/software/miniconda2/envs/metawrap-env/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/hwfssz4/BC_COM_FP/BC_CCP/Micro/software/miniconda2/envs/metawrap-env/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/hwfssz4/BC_COM_FP/BC_CCP/Micro/software/miniconda2/envs/metawrap-env/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/hwfssz4/BC_COM_FP/BC_CCP/Micro/software/miniconda2/envs/metawrap-env/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-Wc0eRD/.nfs00000000908f7818000d30ba'
  Saving HMM info to file.
...

[REFINEMENT.log](https://github.com/bxlab/metaWRAP/files/3064161/REFINEMENT.log)

and the results of stats show as below:
[concoct_bins.stats.txt](https://github.com/bxlab/metaWRAP/files/3064175/concoct_bins.stats.txt)
[maxbin2_bins.stats.txt](https://github.com/bxlab/metaWRAP/files/3064176/maxbin2_bins.stats.txt)
[metabat2_bins.stats.txt](https://github.com/bxlab/metaWRAP/files/3064177/metabat2_bins.stats.txt)
[metawrap_50_10_bins.stats.txt](https://github.com/bxlab/metaWRAP/files/3064178/metawrap_50_10_bins.stats.txt)

**Comment by ursky** [comment]
Your binning results seem normal to me. The `Device or resource busy` error does not seem to affect CheckM performance, don't worry about it.
